version: '3.8' 

services: 
  frontend: 
    build: 
      context: ./frontend 
      dockerfile: Dockerfile 
    ports: 
      - 80:80 
    volumes: 
      - ./frontend:/usr/share/nginx/html 
    depends_on: 
      - backend
  loging:
    image: nginx:latest
    ports:
      - 81:80
    volumes:
      - ./loging:/usr/share/nginx/html
    depends_on:
      - backend
  sarver:
    image: nginx:latest
    ports:
      - 82:80
    volumes:
      - ./sarver:/usr/share/nginx/html
    depends_on:
      - backend